### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by AndrewSav** [jonasvinther/medusa#91]
Running: `medusa export Redacted -o Redacted.yaml`

Getting:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x98 pc=0xc9693d]

goroutine 1 [running]:
github.com/jonasvinther/medusa/pkg/vaultengine.(*Client).SecretRead(0xc0000e3d08, 0xc00001efc0, 0x3b, 0xc0006abd00)
        /home/runner/work/medusa/medusa/pkg/vaultengine/secret_read.go:54 +0x2bd
github.com/jonasvinther/medusa/pkg/vaultengine.(*Client).PathReader(0xc0000e3d08, 0xc000758018, 0xc0003bc0c0, 0x22, 0x0, 0x0)
        /home/runner/work/medusa/medusa/pkg/vaultengine/folder_export.go:79 +0x1cf
github.com/jonasvinther/medusa/pkg/vaultengine.(*Client).PathReader(0xc0000e3d08, 0xc00075a038, 0xc00046ee40, 0x17, 0x0, 0x0)
        /home/runner/work/medusa/medusa/pkg/vaultengine/folder_export.go:67 +0x345
github.com/jonasvinther/medusa/pkg/vaultengine.(*Client).PathReader(0xc0000e3d08, 0xc000222000, 0xc00041c0c0, 0x10, 0x0, 0x0)
        /home/runner/work/medusa/medusa/pkg/vaultengine/folder_export.go:67 +0x345
github.com/jonasvinther/medusa/pkg/vaultengine.(*Client).PathReader(0xc0000e3d08, 0xc0000e3b40, 0xc0001c86f5, 0x1, 0xc000173860, 0x0)
        /home/runner/work/medusa/medusa/pkg/vaultengine/folder_export.go:67 +0x345
github.com/jonasvinther/medusa/pkg/vaultengine.(*Client).FolderExport(0xc000123d08, 0xc0001c86f5, 0x1, 0xc0001c86d0, 0xa, 0xc0001c86f5)
        /home/runner/work/medusa/medusa/pkg/vaultengine/folder_export.go:16 +0x70
github.com/jonasvinther/medusa/cmd.glob..func3(0x111b2e0, 0xc00017ccc0, 0x1, 0x3, 0x0, 0x0)
        /home/runner/work/medusa/medusa/cmd/export.go:47 +0x49e
github.com/spf13/cobra.(*Command).execute(0x111b2e0, 0xc00017cc90, 0x3, 0x3, 0x111b2e0, 0xc00017cc90)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x111ada0, 0xc000059f78, 0xc000123f78, 0x7f662b)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/jonasvinther/medusa/cmd.Execute(...)
        /home/runner/work/medusa/medusa/cmd/cmd.go:59
main.main()
        /home/runner/work/medusa/medusa/main.go:10 +0x39
```

**Comment by AndrewSav** [comment]
Never mind it looks like it was fixed here: https://github.com/jonasvinther/medusa/commit/a5fed2b570d95d607e1160f398aca17fc7555c77
